version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 23506:3306
    container_name: atlantis-jee-database

  payara:
    image: payara/server-full
    volumes:
      - ../payara:/opt/payara/deployments
    ports:
      - 18080:8080
      - 4848:4848
    container_name: altantis-jee-platform

  broker:
    image: rmohr/activemq:latest
    ports:
      - 61616:61616
      - 8161:8161
    container_name: atlantis-broker