version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 23506:3306
    container_name: atlantis-jee-database

  glassfish:
    image: opavlova/glassfish:4.1-jdk8
    volumes:
      - ../glassfish:/usr/local/glassfish4/glassfish/domains/domain1/autodeploy/
    ports:
      - 18080:8080
    container_name: altantis-jee-platform

  broker:
    image: rmohr/activemq:latest
    ports:
      - 61616:61616
      - 8161:8161
    container_name: atlantis-broker